### PR TITLE
Bundle now returns a collection of documents keyed by url instead of a single AST

### PR DESCRIPTION
**Pull request by garlicnation**

### CODE REVIEW

**Comment by justinfagnani** [comment]
What does it mean to "support a collection of documents"? :)

**Comment by usergenic** [comment]
We know we're going to be generating multiple documents as we move sharding logic into bundler so the document set result type feels non-controversial, even if other details are still unknown.

**Comment by justinfagnani** [comment]
I still don't grok "support a collection of documents" though. Support where?

**Comment by justinfagnani** [comment]
Ok, looked at the code, and know I know :)

LGTM

I do want to encourage comments, PR descriptions, commit messages, method and variable names, etc., to be more descriptive and targeted at new readers :)

**Pull request merged**
