### PR TITLE
WIP: vulcanize fix - Issue #406

### PR DESCRIPTION
**Pull request by Bubbit**
Fix for #406 

 - [ ] CHANGELOG.md has been updated
 - [ ] Create new tests & fix old ones where needed

### CODE REVIEW

**Comment by Bubbit** [comment]
I signed it!

**Comment by Bubbit** [comment]
I signed it!

**Comment by usergenic** [comment]
@Bubbit, I took a cue from the rootDocPath inclusion in flatten, but identified a root cause that fixed the issue in your test case.  See https://github.com/Polymer/vulcanize/pull/408 for my fix.  We'll hopefully get reviewed and released quickly.

**Comment by Bubbit** [comment]
As #408 has been fixed, I'm closing this one.

**Pull request closed without merging**
