### PR TITLE
Always use POSIX-style path functions to keep slashes intact.

### PR DESCRIPTION
**Pull request by achimnol**
This is a simple fix for #195. I have confirmed this resolves the issue on Windows.

### CODE REVIEW

**Comment by achimnol** [comment]
I signed it!

**Comment by garlicnation** [comment]
This doesn't work in node 0.10 :'(. Maybe add a check to see if path.posix exists and use that if available?

**Comment by azakus** [comment]
Looks like some kind soul made a 0.10 compatible [path-posix](https://www.npmjs.com/package/path-posix) module by just extracting that portion from 0.12+

**Comment by azakus** [comment]
The merge conflict was a bit confusing after merging #199, so I did it manually in https://github.com/Polymer/vulcanize/commit/774e43ca8ab26c4e1bab2a5c98ee96fd3b90fcaf.

Thanks!

**Pull request closed without merging**
